language: python
sudo: false
deploy:
  provider: pypi
  user: arokem
  password:
    secure: fkh4/O072Kn5rBWGcvaj2p0Ejb9ZOIZJmbZpjfyaKZVTOROBr7G3Bq2aS3KQDmHXPF8xmyezpqOV8o8QHUlZrP8XASYfP16ThgGn9unTLNVlnuOhmxumt1t9dEZfEkMCTvC8X+v9dePYFu9uSLq/sY5pIJVU4y+4FmKiDt18vLvVfgm3VyDnOflK60k6Km2mQUDRmLUx2HzfNJcu9m3J8S0pG6vrLasizPcqLUOFIlVnotkEtookvypFX0Yn4R6P2cQRMLA2+37NAVbHAquMWxH+MCZ/xEEHWfDaa6mBJrH3w+o3Abt4BjcrniAMnMTL72Le2XFE82tV+iogxiOcMxgmnfoFElY0+3Nl7E37LQFkFGpzRPlcXqysHl80IFnwQ4G1w52muRnQKqR+BCJmpIix26C6a22DejRvJ6vBVZxf72btT2fwFx8bba/IwfCMejCsKHjzju1fnIHDP4OEn1MIb3L6OVKwa7/5W6FXN1Yixtt9zCaxNNnZNE8JHjb1AY2ZElp2lttr17+Eo9oWp2ra6r7HPv6ogSaQ4GN6/RYZK1JQQz28oquXIE2I5EAximy89n9Wzt6Kup7i6j1QjWFy3FajxlMYxzMFFmLTW9Nai8cCyF/Scw+fFNHcmx7Vnbh8UBV0PhO45LaYtVebavgd02DzKLfitsnoDUVyJWM=
  on:
    tags: true
    repo: popylar/popylar
env:
  global:
  - PIP_DEPS="coveralls pytest-cov flake8"
python:
- '2.7'
- '3.5'
install:
- pip install $PIP_DEPS
- pip install -r requirements.txt
- python setup.py install
script:
- flake8 --ignore N802,N806 `find . -name \*.py | grep -v setup.py | grep -v /doc/`
- py.test --pyargs popylar --cov-report term-missing --cov=popylar
after_success:
- coveralls
