language: python
sudo: false
deploy:
  provider: pypi
  user: arokem
  password:
    secure: XQD43xb1JKz27fxxaNTuNCsZ/iBSXPPEJimiXkOAOW6Y/NMeGuojW4Yt05AoYznXBdNbNTEfh9NKHVaeGAUuLqsCxsC6JV+UKH19MGLZnSu1yTH1gqOHrYxqH2Ix7GwOA0fYP9JpYsmP0SdMg8wB9Ntk4lO69CjJoXtpTOCN2YkKdHGJbx/z+n+keSkffFBWd8KWLdbcX3Eu2eEH9KHJBrO6u0mHvWY1XDD0O4t0wTXM08EeKQfmvobI7NA2mSurBvkNVa3BCI7X2xyKg5xcLSkOLGodjTzmEBTsxnQ1RK5ffhtql/YX/3n0uCHTBq4BUKLrIsAd6YWH80/iwap/baoUR75kX6BU69BlynbcaUYQ/Wbkvh1OPJWwfdc+TRHNRJ80D8TlozMVkTvyCmRGHU2s/NYTnfcn4n4MDdrNre/Ibh10sSj1w6KdQZqI/22uaC4lgsAqjc8bUJS/zF8/wDFw/wlJ6ElO0Qg/wmPs/f3ngMJeib3+6H05p3uDCNx1dDYqtneutvZ+/JO4oEl4tGPwb3IFG1oatO100nT2nHXdqfq7G2RUghEWKOZr3ivYQnBx1CQpkgJSk9aVCg9Fz8lpbwrmA3k/Uz9rqWWhPKXJX65HQ8DCAUC/p3EzwrHk/P3SH3QCNASQ7ccj9SFCcBVkeoIV8xLvRbkCW6pf5qo=
  on:
    tags: true
    repo: popylar/popylar
env:
  global:
  - PIP_DEPS="coveralls pytest-cov flake8"
python:
- '2.7'
- '3.5'
install:
- pip install $PIP_DEPS
- pip install -r requirements.txt
- python setup.py install
script:
- flake8 --ignore N802,N806 `find . -name \*.py | grep -v setup.py | grep -v /doc/`
- py.test --pyargs popylar --cov-report term-missing --cov=popylar
after_success:
- coveralls
