language: python
sudo: false
deploy:
  provider: pypi
  user: arokem
  password:
    secure: JKKiOtcb6q69kf0ZIQaMkTroe60HhjrPe4/rw71govCR2w8PLAS/IxDyE5zmq9Au0FeJbDm2fJS9B1gsEDGJFX1Q/v9MrjyygZu06aThLh19QfkhxYFldPCynECp5oxrdMPBSRoJWEPe2SDpfVPw6Yw7rgtU0h2p4QqTpG2inGRsOOlcc84U/FjzmZ+mr2KaRr26ZhNUQf4Xec6Cg41QIOvSSNgZaPqmFz01P0IwcHuRPJt/T+suKXI/F9o6NSEDrFfU0KoOYz+7mT2r0ksSOI4DLNB0rXn4ZFwt++e8f+iZJreEelXsVoVupMoZWJX+y4Az9QBQ/QqEWMs18PwhrQup3a0XRFKqEEGUG3lW3POxIGMarqUj5QLVKClvFsIeWCQDbnX4x+OsUUSofK1b1JlecruGJUNX8/ZJRuDyx/CssmnBf5XR/CYn/UBA98CuMszy3xB6NjLRtWUPreosiQ5OFA0K3aZmhyE1Cjbvs/n59QNnx5rm1iwRizgkxsx6O7z8FV0V38J4Dfupv4b5B/KzkXNRajMnY7qD2/rZ67lXveCTgawGxBcLuTW+oyNzEs2ifKpoL/wryHjRAQ23iHnJJhfREshD2/lJXutVAx5+sXAtC5gW2b5eJuf9xFSH9fFoTK7T9kPsNSKNtKyYexut2+aYQ5nQ5hOEh1zGqxw=
  on:
    tags: true
    repo: popylar/popylar
env:
  global:
  - PIP_DEPS="coveralls pytest-cov flake8 doctr"

python:
- '2.7'
- '3.6'

install:
- travis_retry pip install $PIP_DEPS
- travis_retry pip install -r requirements.txt
- travis_retry pip install -e .

script:
- flake8 --ignore N802,N806 `find . -name \*.py | grep -v setup.py | grep -v version.py | grep -v __init__.py | grep -v /docs/`
- py.test --pyargs popylar --cov-report term-missing --cov=popylar

after_success:
- coveralls
